# Generated by Django 4.0.4 on 2022-05-01 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BbsBoard',
        ),
    ]
