# Generated by Django 4.0.4 on 2022-04-30 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_movies_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='cateogry',
            new_name='category',
        ),
    ]
