# Generated by Django 4.0.4 on 2022-04-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_cateogry_movie_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='category',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='year',
            new_name='openingYear',
        ),
        migrations.AddField(
            model_name='movie',
            name='movieType',
            field=models.CharField(blank=True, choices=[('Thriller', 'Thriller')], max_length=20),
        ),
    ]
