# Generated by Django 4.0.4 on 2022-04-30 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0001_initial'),
        ('movies', '0004_rename_category_movie_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='directors.director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movieType',
            field=models.CharField(blank=True, choices=[('Action', '액션'), ('Thriller', '스릴러')], max_length=20),
        ),
    ]
