# Generated by Django 4.0.4 on 2022-04-30 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0001_initial'),
        ('movies', '0007_alter_movie_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director_id',
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='directors.director'),
        ),
    ]
