# Generated by Django 4.0.4 on 2022-04-30 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_remove_movie_director_id_movie_director'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='director',
            new_name='director_id',
        ),
    ]
